<?php

namespace ContainerARDvffj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiControllerJsonService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ApiControllerJson' shared autowired service.
     *
     * @return \App\Controller\ApiControllerJson
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/ApiControllerJson.php';

        return $container->services['App\\Controller\\ApiControllerJson'] = new \App\Controller\ApiControllerJson(($container->privates['debug.serializer'] ?? self::getDebug_SerializerService($container)));
    }
}
