<?php

namespace ContainerARDvffj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CardController' shared autowired service.
     *
     * @return \App\Controller\CardController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/CardController.php';

        return $container->services['App\\Controller\\CardController'] = new \App\Controller\CardController();
    }
}
