controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

card_landing:
    path: /card
    controller: App\Controller\CardSessionController::landingPage

session_content:
    path: /session
    controller: App\Controller\CardSessionController::sessionPage

session_delete:
    path: /session/delete
    controller: App\Controller\CardSessionController::deleteSession

card_deck_show:
    path: /card/deck
    controller: App\Controller\CardSessionController::showDeck

card_deck_shuffle:
    path: /card/deck/shuffle
    controller: App\Controller\CardSessionController::shuffleDeck

card_deck_draw:
    path: /card/deck/draw
    controller: App\Controller\CardSessionController::drawCard

card_deck_draw_multiple:
    path: /card/deck/draw/{number}
    controller: App\Controller\CardSessionController::drawMultipleCards
    requirements:
        number: '\d+'
