<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKPU6axT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKPU6axT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKPU6axT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKPU6axT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKPU6axT\App_KernelDevDebugContainer([
    'container.build_hash' => 'KPU6axT',
    'container.build_id' => '4c31dbb1',
    'container.build_time' => 1713799112,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKPU6axT');
