<?php

namespace ContainerKPU6axT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLuckyControllerJsonService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\LuckyControllerJson' shared autowired service.
     *
     * @return \App\Controller\LuckyControllerJson
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/LuckyControllerJson.php';

        return $container->services['App\\Controller\\LuckyControllerJson'] = new \App\Controller\LuckyControllerJson();
    }
}
