<?php

namespace ContainerKZdvz9s;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuoteControllerJsonService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\QuoteControllerJson' shared autowired service.
     *
     * @return \App\Controller\QuoteControllerJson
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/QuoteControllerJson.php';

        return $container->services['App\\Controller\\QuoteControllerJson'] = new \App\Controller\QuoteControllerJson();
    }
}
