<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWNjeQfp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWNjeQfp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWNjeQfp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWNjeQfp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWNjeQfp\App_KernelDevDebugContainer([
    'container.build_hash' => 'WNjeQfp',
    'container.build_id' => '467bb102',
    'container.build_time' => 1712268072,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWNjeQfp');
